openapi: 3.0.3
info:
  title: API Service
  description: Minimal API service with Express and TypeScript
  version: 1.0.0
  contact:
    name: Your Name
    email: your.email@example.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:3000
    description: Local development server
  - url: https://api.example.com
    description: Production server

paths:
  /healthz:
    get:
      summary: Health check endpoint
      description: Returns the health status of the API
      operationId: healthCheck
      tags:
        - Health
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  timestamp:
                    type: string
                    format: date-time
                    example: '2025-10-06T00:00:00.000Z'
                  uptime:
                    type: number
                    example: 123.456

  /:
    get:
      summary: API information
      description: Returns basic information about the API
      operationId: getApiInfo
      tags:
        - Info
      responses:
        '200':
          description: API information
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: API Service is running
                  version:
                    type: string
                    example: 1.0.0
                  endpoints:
                    type: object
                    properties:
                      health:
                        type: string
                        example: /healthz
                      api:
                        type: string
                        example: /api/v1

  /api/v1/status:
    get:
      summary: API status
      description: Returns the current status of the API
      operationId: getStatus
      tags:
        - Status
      responses:
        '200':
          description: API status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: active
                  environment:
                    type: string
                    example: development

  /api/v1/echo:
    post:
      summary: Echo endpoint
      description: Returns the received request body with a timestamp
      operationId: echo
      tags:
        - Examples
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
              example:
                message: Hello API
      responses:
        '200':
          description: Echo response
          content:
            application/json:
              schema:
                type: object
                properties:
                  received:
                    type: object
                    additionalProperties: true
                  timestamp:
                    type: string
                    format: date-time

components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
      required:
        - error
        - message

tags:
  - name: Health
    description: Health check endpoints
  - name: Info
    description: API information
  - name: Status
    description: Status endpoints
  - name: Examples
    description: Example endpoints
