name: Validate Documentation

on:
  pull_request:
    branches: [master, main]
  push:
    branches: [master, main]
  schedule:
    # Run weekly on Sundays at 2am UTC to check all docs links
    - cron: '0 2 * * 0'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run markdown linting
        run: npm run lint:md
        continue-on-error: true

      - name: Check README links
        run: npm run check:links
        continue-on-error: true

      - name: Check all documentation links (weekly)
        if: github.event_name == 'schedule'
        run: npm run check:links:all
        continue-on-error: true
